### ISSUE TITLE
Missing shows when scanner cannot guess title?

### ISSUE THREAD

**Issue by Eidenz** [zoriya/Kyoo#455]
### Kyoo's version

v4.5.0

### What happened?

As the title says, a lot of my shows are not showing up at all in the UI, and I can see them in the Scanner logs with "Could not guess title".

For example: `Could not guess title, found: ['86', 'Eighty Six']`.
About half my animes are missing to tell how common it seems to be on my end?

**Comment by zoriya** [comment]
Can you show me an example of your paths? It should be an easy fix with a repo.

**Comment by Eidenz** [comment]
Here are two examples that could not be guessed.

`Anime/86 - Eighty Six/Season 1/...`
`Anime/Frieren - Beyond Journey's End/Season 1/...`

Filenames of actual episodes are inconsistent depending on the source. But the folders always have the name of the show and which season as you can see.
This folder structure is typical behavior of *Arr services.

**Comment by zoriya** [comment]
Please give a complete path with filename. I could test with my assumptions but I can be sure to correct your case if I have the complete filename (only one or two examples are needed).

**Comment by Eidenz** [comment]
`/video/Anime/Frieren - Beyond Journey's End/Season 1/Frieren Beyond Journeys End S01E08 Frieren the Slayer 1080p AMZN WEB-DL DDP2.0 H 264-VARYG (Sousou no Frieren, Multi-Subs).mkv`
`/video/Anime/86 - Eighty Six/Season 1/86 - Eighty Six - S01E01 - Undertaker WEBDL-1080p.mkv`

**Comment by zoriya** [comment]
I pushed a fix, please report back if you have other issues.

**Comment by Eidenz** [comment]
I have found a couple more issues related to this.

1. Kyoo could not find the episode despite it existing and having an absolute number too (244377):
![image](https://github.com/zoriya/Kyoo/assets/27901016/0c531859-b162-4c61-bf70-ebe5d0113e6b)
![image](https://github.com/zoriya/Kyoo/assets/27901016/7f0411ed-6246-49db-83e9-82cc8ae902bf)

2. It seems some shows still can't be found despite latest PR patch:
![image](https://github.com/zoriya/Kyoo/assets/27901016/59eaa24a-7451-4971-8337-4e979b61cb1f)
![image](https://github.com/zoriya/Kyoo/assets/27901016/de179c93-042f-4654-ace5-8bbcaa9b5473)

**Comment by zoriya** [comment]
The first issue, themoviedb returned the Oshi no Ko drama and not the anime x(. Will look into fixing that, but that may be tricky since they have the same names.

The second issue is because TheMovieDb has stored everything in a single season. Does the S02 naming for Jujustu works on jellyfin?

**Comment by Eidenz** [comment]
Yes, it detects correctly in Jellyfin. Everything I mentioned here so far doesn't occur in Jellyfin, which has a 100% detection rate on my stuff.
Jellyfin is known to integrate well with Arr services, so they might have special tweak with folder structures when it can't rely on DB? I also added the following to it:
![image](https://github.com/zoriya/Kyoo/assets/27901016/cb49bd0a-4464-4726-9bb9-728a96acc7bb)
